language: node_js

services:
  - mongodb

node_js:
  - 6

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
>>>>>>> 6151f655346fe5062813d963e3863b9bafa2afcc

script:
  - npm run lint
  - npm run coverage
  - npm run codecov
